#!/bin/bash

#SBATCH --partition=gpu_mig
#SBATCH --gpus=1
#SBATCH --job-name=Test
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=9
#SBATCH --time=01:00:00
#SBATCH --output=output/slurm_output_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1

source activate hyperbolic

export WANDB_API_KEY=868e3906005e2c816a758fcbc88d5098dabc27be

export PYTHONPATH=$(pwd)

srun python tests/test_train.py --num-heads 1 
srun python tests/test_train.py --num-heads 2
srun python tests/test_train.py --num-heads 4